### ISSUE TITLE
Database Migration Scripts are not executed

### ISSUE THREAD

**Issue by rabauss** [Fuzzyma/contao-database-commands-bundle#7]
Unfortunately, the Database Update Scripts are not executed with this extension.
If you update a contao 4.4 to 4.8 - the migrations are missing (https://github.com/contao/contao/tree/4.8/installation-bundle/src/Database).

So, you need to call the contao installer manually and afterwards the extension can be used as before. If you just execute the schema updates with this extension, e.g. you will have some trouble with migration of important parts of images.

The solution would be a little bit tricky, because the necessary method is private (https://github.com/contao/contao/blob/4.8/installation-bundle/src/Controller/InstallationController.php#L374)

But there will be a core solution in contao 4.9 for database migrations!
You could add an hint in the readme, that there can be some trouble if the extension executes the schema migration but not the database migrations via scripts.

**Comment by Fuzzyma** [comment]
Hey @rabauss, I wrote this bundle years ago and didnt keep track of the evolution of contao.
As far as I can see the private method is not that complicated so if you cannot use it, just replicate the behavior.
Is this migration thing a new one? I cannot remember using it 3 years ago.
Beside that, does this bundle still work? That would be awesome :)

// EDIT: 

The method contains this:
```php
        if ($this->container->get('contao.install_tool')->isFreshInstallation()) {
            return;
        }
```

Is this even run when the installation is fresh? Because for me the bundle was for setting up a new installation. Ofc it can also be used to update the database only but I never used it that way.
So: Is it correct to say, that your issue only arises when using a contao installation which is not fresh?

**Comment by rabauss** [comment]
We use this extension, to do database schema updates on existing systems via gitlab-ci.
And yes, just for schema updates it's still working :-)

I also didn't know the migrations until the update to contao 4.8. But there are also migrations from 3.5 to 4 - so it's no new thing :-D

For now we disabled the extension before updating to 4.8 and then we called the installer manually. afterwards the extension behaves like expected - although it won't do any future migrations!

You're right that the private method is not that complicated, but I have no time for a PR and we now know that we have to disable before big update to 4.8.

**Comment by Fuzzyma** [comment]
Man thats awesome! Cool to see that it is actually used :). My problem is, that I am totally out of scope to do this atm so I would need to read into contao again. And there is no use for me in that atm.
I am happy that you found a solution. Maybe I will tackle that one day but maybe not :D.
Its funny, when I wrote this, they said, that this will be soon possible in contao but I still dont see this feature in the core ^^

**Comment by rabauss** [comment]
It will come in Contao 4.9 (https://www.youtube.com/watch?v=10RwlTDaKTk&feature=youtu.be&t=2442)

**Comment by rabauss** [comment]
This Extension ist really obsolet with Contao 4.9.
Thanks for the work!

**Comment by Fuzzyma** [comment]
Only took them 4 years :D. They told me back then, that I shouldnt bother with this because they will have this feature soon. Glad that it finally shipped^^
